# Generated by Django 5.0.4 on 2024-05-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='madein',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
