# Generated by Django 5.0.4 on 2024-05-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_name_car_model_car_madein'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.TextField(default='Copy Image URL', max_length=300),
        ),
        migrations.AlterField(
            model_name='car',
            name='madein',
            field=models.CharField(default='Unknown ', max_length=100),
        ),
    ]
