# Generated by Django 5.0.4 on 2024-05-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_car_image_alter_car_madein'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Available Rental Date')),
                ('rental', models.CharField(choices=[('D', 'Day-time only, 7 AM - 3 PM'), ('N', 'Night-time only, 3 PM - 11 PM'), ('A', 'All-day, 7 AM - 11 PM')], default='D', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
