# Generated by Django 5.0.4 on 2024-05-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_option_alter_rental_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='options',
            field=models.ManyToManyField(to='main_app.option'),
        ),
    ]
