# Generated by Django 5.0.4 on 2024-05-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
